import Foundation
import XCTest
@testable import Wand

final class TaskBoardTests: XCTestCase {
    func testBoardTaskDecoderReadsWorkspaceAgentAndSessions() throws {
        let json = """
        {
          "id": "task-1",
          "workspaceId": "ws-1",
          "identifier": "TASK-1",
          "title": "修顶栏",
          "description": "对齐 macOS",
          "status": "doing",
          "priority": "high",
          "labels": ["ui"],
          "sortOrder": 2,
          "agent": { "provider": "codex", "model": "default", "thinkingEffort": "deep" },
          "sessionIds": ["sess-1"],
          "sessions": [{
            "id": "sess-1",
            "provider": "codex",
            "sessionKind": "structured",
            "title": "修顶栏",
            "status": "running",
            "cwd": "/repo",
            "model": "gpt-5",
            "thinkingEffort": "deep"
          }],
          "workspace": { "id": "ws-1", "name": "wand", "cwd": "/repo" }
        }
        """.data(using: .utf8)!
        let task = try JSONDecoder().decode(WandBoardTask.self, from: json)
        XCTAssertEqual(task.id, "task-1")
        XCTAssertEqual(task.workspaceId, "ws-1")
        XCTAssertEqual(task.status, "doing")
        XCTAssertEqual(task.agent?.provider, "codex")
        XCTAssertEqual(task.workspace?.name, "wand")
        XCTAssertEqual(task.sessions.first?.id, "sess-1")
        XCTAssertTrue(task.sessions.first?.isStructured == true)
        // 老服务端不返回 mode / kind 时按「provider 支持的默认值 + 结构化」兜底，
        // 不能让整条任务解码失败；Codex 只支持全限，所以这里落到 full-access。
        XCTAssertEqual(task.agent?.mode, WandBoardAgentMode.fullAccess.rawValue)
        XCTAssertEqual(task.agent?.kind, WandBoardAgentKind.structured.rawValue)
    }

    func testBoardTaskDecoderAllowsUnassignedProjectAndAgent() throws {
        let json = #"{"id":"task-2","title":"草稿"}"#.data(using: .utf8)!
        let task = try JSONDecoder().decode(WandBoardTask.self, from: json)
        XCTAssertNil(task.workspaceId)
        XCTAssertNil(task.agent)
        XCTAssertEqual(task.status, "todo")
        XCTAssertEqual(task.priority, "none")
        XCTAssertTrue(task.sessions.isEmpty)
        // 老服务端不返回 titleSource，按用户手写处理。
        XCTAssertEqual(task.titleSource, "user")
        XCTAssertNil(task.milestone)
        XCTAssertNil(task.dueDate)
    }

    func testBoardTaskDecoderKeepsUsableSessionsWhenOneIsMalformed() throws {
        // 真实服务端 payload 里会话可能缺 provider、甚至整个元素缺 id，
        // 坏元素只丢自己，不带踢同任务其它会话。
        let json = """
        {
          "id": "task-5",
          "status": "doing",
          "sessionIds": ["sess-1", "", "sess-3"],
          "sessions": [
            { "id": "sess-1", "provider": "", "sessionKind": "pty", "status": "running" },
            { "provider": "codex", "status": "running" },
            { "id": "sess-3", "provider": "pi", "sessionKind": "structured", "status": "running" }
          ]
        }
        """.data(using: .utf8)!
        let task = try JSONDecoder().decode(WandBoardTask.self, from: json)
        XCTAssertEqual(task.sessions.map(\.id), ["sess-1", "sess-3"])
        XCTAssertEqual(task.sessions.first?.provider, "")
        XCTAssertFalse(task.sessions[0].isStructured)
        XCTAssertTrue(task.sessions[1].isStructured)
    }

    func testBoardTaskDecoderReadsAutoGeneratedTitleSource() throws {
        let json = #"{"id":"task-3","title":"根据描述生成的标题","titleSource":"auto"}"#.data(using: .utf8)!
        let task = try JSONDecoder().decode(WandBoardTask.self, from: json)
        XCTAssertEqual(task.titleSource, "auto")
    }

    func testBoardTaskDecoderReadsMilestoneAndDueDate() throws {
        let json = """
        {
          "id": "task-4",
          "title": "带迭代的任务",
          "dueDate": "2026-09-30",
          "milestoneId": "ms-1",
          "milestone": { "id": "ms-1", "name": "v5.0 发布", "isDefault": false }
        }
        """.data(using: .utf8)!
        let task = try JSONDecoder().decode(WandBoardTask.self, from: json)
        XCTAssertEqual(task.dueDate, "2026-09-30")
        XCTAssertEqual(task.milestoneId, "ms-1")
        XCTAssertEqual(task.milestone?.name, "v5.0 发布")
        XCTAssertEqual(task.milestone?.isDefault, false)
    }

    func testBoardLabelsCoverColumns() {
        XCTAssertEqual(WandBoardStatus.columns.map(\.rawValue), ["todo", "doing", "done"])
        XCTAssertEqual(WandBoardStatus.todo.label, "等待认领")
        XCTAssertEqual(WandBoardStatus.doing.label, "处理中")
        XCTAssertEqual(WandBoardStatus.done.label, "等你确认")
        XCTAssertEqual(WandBoardStatus.archived.label, "归档任务")
        XCTAssertFalse(WandBoardStatus.todo.isClosed)
        XCTAssertTrue(WandBoardStatus.done.isClosed)
        XCTAssertTrue(WandBoardStatus.archived.isClosed)
        XCTAssertEqual(WandBoardPriority.urgent.label, "紧急")
        XCTAssertEqual(wandBoardProviderLabel("pi"), "Pi")
        XCTAssertEqual(wandBoardEffortLabel("deep"), "深入")
        XCTAssertEqual(wandBoardEffortLabel("off"), "关闭")
        // 未知值原样透出，别把服务端新加的档位显示成「关闭」。
        XCTAssertEqual(wandBoardEffortLabel("turbo"), "turbo")
        XCTAssertEqual(wandBoardProviderLabel("unknown"), "unknown")
        XCTAssertEqual(wandBoardSessionStatusLabel("running"), "进行中")
    }

    func testBoardViewLabelsMatchWeb() {
        XCTAssertEqual(WandBoardView.allCases.map(\.label), ["概览", "看板", "列表", "甘特图"])
        XCTAssertEqual(WandBoardGanttZoom.day.days, 14)
        XCTAssertEqual(WandBoardGanttZoom.week.days, 42)
        XCTAssertEqual(WandBoardGanttZoom.month.days, 90)
    }

    // MARK: 派发 Agent

    func testAgentModeIsClampedToWhatProviderSupports() {
        // Codex 只有「全限」一个有效值，其余 provider 三种都能用。
        XCTAssertEqual(WandBoardAgentMode.supported(provider: "codex"), [.fullAccess])
        XCTAssertEqual(WandBoardAgentMode.supported(provider: "claude").count, 3)
        XCTAssertEqual(WandBoardAgentMode.normalize(provider: "codex", value: "default"), "full-access")
        XCTAssertEqual(WandBoardAgentMode.normalize(provider: "claude", value: nil), "default")
        XCTAssertEqual(WandBoardAgentMode.normalize(provider: "claude", value: "乱值"), "default")
        XCTAssertEqual(WandBoardAgentMode.label(forValue: "managed"), "托管")
        XCTAssertEqual(WandBoardAgentMode.label(forValue: ""), "标准")
    }

    func testAgentWithProviderKeepsModelButFixesMode() {
        let agent = WandBoardTaskAgent(
            provider: "claude",
            model: "opus",
            thinkingEffort: "deep",
            mode: WandBoardAgentMode.managed.rawValue
        )
        let codex = agent.withProvider("codex")
        XCTAssertEqual(codex.provider, "codex")
        XCTAssertEqual(codex.model, "opus")
        XCTAssertEqual(codex.mode, "full-access")
        XCTAssertEqual(codex.thinkingEffort, "deep")
        XCTAssertEqual(codex.jsonObject()["kind"] as? String, "structured")
    }

    func testModelOptionsAlwaysIncludeDefault() {
        XCTAssertEqual(
            wandBoardModelOptions(from: nil, provider: "claude").first?.id,
            "default"
        )
        XCTAssertFalse(wandBoardModelOptions(from: nil, provider: "pi").isEmpty)
    }

    func testSessionsGroupByTheAgentsThatRan() {
        let json = """
        {
          "id": "task-9",
          "title": "多 Agent",
          "agent": { "provider": "claude", "model": "opus", "thinkingEffort": "deep" },
          "sessions": [
            { "id": "s1", "provider": "claude", "title": "修登录", "status": "running", "model": "opus", "thinkingEffort": "deep" },
            { "id": "s2", "provider": "claude", "title": "补测试", "status": "exited", "model": "sonnet", "thinkingEffort": "off" },
            { "id": "s3", "provider": "codex", "title": "实现 API", "status": "idle", "model": "gpt-5", "thinkingEffort": "standard" }
          ]
        }
        """.data(using: .utf8)!
        let task = try! JSONDecoder().decode(WandBoardTask.self, from: json)
        let groups = wandBoardSessionGroups(sessions: task.sessions, assigned: task.agent)
        XCTAssertEqual(groups.map(\.provider), ["claude", "codex"])
        XCTAssertEqual(groups[0].sessions.map(\.id), ["s1", "s2"])
        XCTAssertEqual(groups[1].sessions.map(\.id), ["s3"])
        let pending = wandBoardSessionGroups(
            sessions: [],
            assigned: WandBoardTaskAgent(provider: "pi", model: "default", thinkingEffort: "off")
        )
        XCTAssertEqual(pending.count, 1)
        XCTAssertEqual(pending.first?.provider, "pi")
        XCTAssertTrue(pending.first?.sessions.isEmpty == true)
        // 卡片上的 Agent 胶囊：跑过或已指派的工具各一个。
        XCTAssertEqual(wandBoardListAgents(sessions: task.sessions, assigned: task.agent).map(\.provider), ["claude", "codex"])
    }

    // MARK: 拖拽与派发时机

    func testDropDispatchOnlyForTheFirstTripToDoing() {
        XCTAssertTrue(wandBoardCreateDispatches(status: "doing"))
        XCTAssertFalse(wandBoardCreateDispatches(status: "todo"))
        XCTAssertTrue(wandBoardDropDispatches(status: "doing", sessionCount: 0))
        // 已经跑过的卡再拖回来只改状态，避免拖一次就多开一个 session。
        XCTAssertFalse(wandBoardDropDispatches(status: "doing", sessionCount: 1))
        XCTAssertFalse(wandBoardDropDispatches(status: "done", sessionCount: 0))
    }

    func testDropDispatchPromptPrefersDescriptionThenTitle() {
        XCTAssertEqual(
            wandBoardDropDispatchPrompt(title: "标题", description: "  描述  "),
            "描述"
        )
        XCTAssertEqual(wandBoardDropDispatchPrompt(title: "标题", description: " "), "标题")
        XCTAssertEqual(wandBoardDropDispatchPrompt(title: " ", description: ""), "执行此任务")
    }

    // MARK: 筛选、搜索与分组

    func testFiltersAndSearchMatchWebSemantics() throws {
        let json = """
        [
          {"id":"a","title":"修登录","description":"OAuth","status":"todo","priority":"high",
           "labels":["缺陷"],"workspaceId":"ws-1","dueDate":"2026-09-01"},
          {"id":"b","title":"补测试","status":"doing","priority":"low","labels":["测试"],"workspaceId":"ws-2"},
          {"id":"c","title":"写文档","status":"archived","priority":"none"}
        ]
        """.data(using: .utf8)!
        let tasks = try JSONDecoder().decode([WandBoardTask].self, from: json)
        let all = WandBoardFilters.empty

        XCTAssertTrue(wandBoardMatches(task: tasks[0], query: "", workspaceId: "", filters: all))
        XCTAssertTrue(wandBoardMatches(task: tasks[0], query: "oauth", workspaceId: "", filters: all))
        XCTAssertFalse(wandBoardMatches(task: tasks[2], query: "缺陷", workspaceId: "", filters: all))
        XCTAssertTrue(wandBoardMatches(task: tasks[0], query: "缺陷", workspaceId: "", filters: all))
        XCTAssertFalse(wandBoardMatches(task: tasks[1], query: "", workspaceId: "ws-1", filters: all))

        var statuses = all
        statuses.statuses = ["archived"]
        XCTAssertTrue(wandBoardMatches(task: tasks[2], query: "", workspaceId: "", filters: statuses))
        XCTAssertFalse(wandBoardMatches(task: tasks[1], query: "", workspaceId: "", filters: statuses))

        var priorities = all
        priorities.priorities = ["high"]
        XCTAssertTrue(wandBoardMatches(task: tasks[0], query: "", workspaceId: "", filters: priorities))
        XCTAssertFalse(wandBoardMatches(task: tasks[1], query: "", workspaceId: "", filters: priorities))

        var labels = all
        labels.labels = ["测试"]
        XCTAssertTrue(wandBoardMatches(task: tasks[1], query: "", workspaceId: "", filters: labels))
        XCTAssertFalse(wandBoardMatches(task: tasks[0], query: "", workspaceId: "", filters: labels))
        XCTAssertEqual(labels.count, 1)
        XCTAssertTrue(labels.isActive)

        let grouped = wandBoardGroup(tasks: tasks)
        XCTAssertEqual(grouped["todo"]?.count, 1)
        XCTAssertEqual(grouped["doing"]?.count, 1)
        XCTAssertEqual(grouped["archived"]?.count, 1)
        XCTAssertEqual(grouped["done"]?.count, 0)
        XCTAssertEqual(Set(wandBoardCollectLabels(tasks: tasks)), ["测试", "缺陷"])
    }

    func testSearchScopeMatchesWebAndExcludesProjectName() throws {
        let json = """
        [
          {"id":"a","title":"修登录","identifier":"TASK-1","description":"OAuth","labels":["缺陷"],
           "workspaceId":"ws-1","workspace":{"id":"ws-1","name":"wand","cwd":"/repo"}}
        ]
        """.data(using: .utf8)!
        let task = try JSONDecoder().decode([WandBoardTask].self, from: json)[0]
        // 标题 / 编号 / 描述 / 标签命中（与 Web filterIssues 一致）。
        XCTAssertTrue(wandBoardMatches(task: task, query: "修登录", workspaceId: "", filters: .empty))
        XCTAssertTrue(wandBoardMatches(task: task, query: "task-1", workspaceId: "", filters: .empty))
        XCTAssertTrue(wandBoardMatches(task: task, query: "oauth", workspaceId: "", filters: .empty))
        XCTAssertTrue(wandBoardMatches(task: task, query: "缺陷", workspaceId: "", filters: .empty))
        // 项目名不在搜索范围内。
        XCTAssertEqual(task.workspace?.name, "wand")
        XCTAssertFalse(wandBoardMatches(task: task, query: "wand", workspaceId: "", filters: .empty))
    }

    func testNewTaskDefaultsToLowPriorityLikeWeb() {
        // Web `DEFAULT_WAND_TASK_PRIORITY`：没挑优先级时默认「低」。
        XCTAssertEqual(WandBoardDraft().priority, WandBoardPriority.low.rawValue)
    }

    func testCreateMoreKeepsOnlyProjectStatusAndAgent() {
        var draft = WandBoardDraft()
        draft.workspaceId = "ws-9"
        draft.status = WandBoardStatus.doing.rawValue
        draft.priority = WandBoardPriority.urgent.rawValue
        draft.milestoneId = "ms-1"
        draft.dueDate = "2026-09-30"
        draft.labels = "缺陷, 界面"
        draft.agent = WandBoardTaskAgent(provider: "pi", model: "default", thinkingEffort: "max", mode: "managed", kind: "structured")

        let next = wandBoardDraftAfterCreateMore(draft)
        XCTAssertEqual(next.workspaceId, "ws-9")
        XCTAssertEqual(next.status, WandBoardStatus.doing.rawValue)
        XCTAssertEqual(next.agent.provider, "pi")
        XCTAssertEqual(next.priority, WandBoardPriority.low.rawValue)
        XCTAssertEqual(next.milestoneId, "")
        XCTAssertEqual(next.dueDate, "")
        XCTAssertEqual(next.labels, "")
        XCTAssertTrue(next.isEmpty)
    }

    func testLabelTonesFollowWebConvention() {
        XCTAssertEqual(wandBoardLabelTone("缺陷"), .bug)
        XCTAssertEqual(wandBoardLabelTone("Bug"), .bug)
        XCTAssertEqual(wandBoardLabelTone("特性"), .feature)
        XCTAssertEqual(wandBoardLabelTone("测试"), .neutral)
        XCTAssertEqual(wandBoardLabelTone("特性"), .feature)
        XCTAssertEqual(wandBoardLabelName("缺陷"), "BUG")
        XCTAssertEqual(wandBoardLabelName("bug"), "BUG")
        XCTAssertEqual(wandBoardLabelName("特性"), "新功能")
        XCTAssertEqual(wandBoardLabelName("测试"), "测试")
    }

    // MARK: 日期与统计

    func testOverdueOnlyCountsOpenTasks() throws {
        let json = """
        [
          {"id":"a","title":"逾期","status":"todo","dueDate":"2020-01-01"},
          {"id":"b","title":"已确认","status":"done","dueDate":"2020-01-01"},
          {"id":"c","title":"已归档","status":"archived","dueDate":"2020-01-01"},
          {"id":"d","title":"没日期","status":"doing","priority":"urgent"}
        ]
        """.data(using: .utf8)!
        let tasks = try JSONDecoder().decode([WandBoardTask].self, from: json)
        XCTAssertTrue(wandBoardIsOverdue(tasks[0].dueDate, status: tasks[0].status))
        XCTAssertFalse(wandBoardIsOverdue(tasks[1].dueDate, status: tasks[1].status))
        XCTAssertFalse(wandBoardIsOverdue(tasks[2].dueDate, status: tasks[2].status))
        XCTAssertFalse(wandBoardIsOverdue(nil, status: "todo"))
        XCTAssertEqual(wandBoardDueStamp("2026-09-30"), "9/30")
        XCTAssertEqual(wandBoardDueStamp(nil), "")

        let stats = wandBoardStats(tasks: tasks)
        XCTAssertEqual(stats.total, 4)
        XCTAssertEqual(stats.todo, 1)
        XCTAssertEqual(stats.doing, 1)
        XCTAssertEqual(stats.done, 1)
        XCTAssertEqual(stats.remaining, 2)
        XCTAssertEqual(stats.overdue, 1)
        XCTAssertEqual(stats.high, 1)
    }

    func testGanttSpanStaysInsideTheRange() throws {
        let json = """
        [
          {"id":"a","title":"有截止","status":"doing","createdAt":"2026-09-20T10:00:00Z","dueDate":"2026-09-24"},
          {"id":"b","title":"没有截止","status":"todo","createdAt":"2026-09-21T10:00:00Z"},
          {"id":"c","title":"很久以前","status":"doing","createdAt":"2020-01-01T10:00:00Z"}
        ]
        """.data(using: .utf8)!
        let tasks = try JSONDecoder().decode([WandBoardTask].self, from: json)
        for zoom in WandBoardGanttZoom.allCases {
            let range = wandBoardGanttRange(zoom: zoom)
            XCTAssertEqual(range.days, zoom.days)
            XCTAssertEqual(range.columns.count, zoom.days)
            for task in tasks {
                let span = wandBoardGanttSpan(task: task, range: range)
                XCTAssertGreaterThanOrEqual(span.offset, 0)
                XCTAssertGreaterThanOrEqual(span.length, 1)
                XCTAssertLessThanOrEqual(span.offset + span.length, range.days)
            }
        }
    }

    func testProgressSeriesIsMonotonic() throws {
        let json = """
        [
          {"id":"a","title":"旧","status":"done","createdAt":"2026-08-01T00:00:00Z","updatedAt":"2026-08-10T00:00:00Z"},
          {"id":"b","title":"新","status":"todo","createdAt":"2026-09-01T00:00:00Z"}
        ]
        """.data(using: .utf8)!
        let tasks = try JSONDecoder().decode([WandBoardTask].self, from: json)
        let series = wandBoardProgressSeries(tasks: tasks)
        XCTAssertEqual(series.count, 13)
        for index in 1..<series.count {
            XCTAssertGreaterThanOrEqual(series[index].scope, series[index - 1].scope)
            XCTAssertGreaterThanOrEqual(series[index].started, series[index - 1].started)
            XCTAssertGreaterThanOrEqual(series[index].completed, series[index - 1].completed)
        }
        XCTAssertEqual(series.last?.scope, 2)
        XCTAssertEqual(series.last?.completed, 1)
    }

    func testMilestoneVisibilityFollowsWorkspaceScope() {
        let global = makeMilestone(["id": "ms-1", "name": "全局迭代"])
        let scoped = makeMilestone(["id": "ms-2", "name": "本项目迭代", "workspaceId": "ws-1"])
        let other = makeMilestone(["id": "ms-3", "name": "别的项目", "workspaceId": "ws-2"])
        XCTAssertTrue(global.isVisible(for: nil))
        XCTAssertTrue(global.isVisible(for: "ws-1"))
        XCTAssertTrue(scoped.isVisible(for: "ws-1"))
        XCTAssertFalse(scoped.isVisible(for: "ws-2"))
        XCTAssertFalse(other.isVisible(for: "ws-1"))
        // 不选工作区时全部可见。
        XCTAssertTrue(other.isVisible(for: ""))
    }

    // MARK: 视图状态持久化

    func testViewStateAndDisplayRoundTrip() {
        let previous = wandBoardReadViewState()
        let previousDisplay = wandBoardReadDisplay()
        defer {
            wandBoardWriteViewState(previous)
            wandBoardWriteDisplay(previousDisplay)
        }

        var state = WandBoardViewState.default
        state.view = .gantt
        state.query = "登录"
        state.workspaceId = "ws-1"
        state.filters.statuses = ["doing"]
        state.filters.labels = ["缺陷"]
        wandBoardWriteViewState(state)
        let restored = wandBoardReadViewState()
        XCTAssertEqual(restored.view, .gantt)
        XCTAssertEqual(restored.query, "登录")
        XCTAssertEqual(restored.workspaceId, "ws-1")
        XCTAssertEqual(restored.filters.statuses, ["doing"])
        XCTAssertEqual(restored.filters.labels, ["缺陷"])

        var display = WandBoardDisplay.default
        display.body = true
        display.mainStatuses = ["todo", "doing"]
        wandBoardWriteDisplay(display)
        let restoredDisplay = wandBoardReadDisplay()
        XCTAssertTrue(restoredDisplay.body)
        XCTAssertEqual(restoredDisplay.mainStatuses, ["todo", "doing"])

        // 主列全被清空是脏数据：读回来时必须回落到默认三列，看板不能变空。
        UserDefaults.standard.set(
            try? JSONSerialization.data(withJSONObject: ["body": false, "mainStatuses": []]),
            forKey: "wand.desktop.taskBoard.display"
        )
        XCTAssertEqual(wandBoardReadDisplay().mainStatuses, Set(WandBoardStatus.columns.map(\.rawValue)))
    }
}

/// 测试里的便捷构造：走真正的解码路径，避免手写 init 绕过容错逻辑。
private func makeMilestone(_ json: [String: Any]) -> WandBoardMilestone {
    let data = try! JSONSerialization.data(withJSONObject: json)
    return try! JSONDecoder().decode(WandBoardMilestone.self, from: data)
}
