import Foundation
import XCTest
@testable import Wand

final class TaskBoardTests: XCTestCase {
    func testBoardTaskDecoderReadsWorkspaceAgentAndSessions() throws {
        let json = """
        {
          "id": "task-1",
          "workspaceId": "ws-1",
          "identifier": "TASK-1",
          "title": "修顶栏",
          "description": "对齐 macOS",
          "status": "doing",
          "priority": "high",
          "labels": ["ui"],
          "sortOrder": 2,
          "agent": { "provider": "codex", "model": "default", "thinkingEffort": "deep" },
          "sessionIds": ["sess-1"],
          "sessions": [{
            "id": "sess-1",
            "provider": "codex",
            "sessionKind": "structured",
            "title": "修顶栏",
            "status": "running",
            "cwd": "/repo",
            "model": "gpt-5",
            "thinkingEffort": "deep"
          }],
          "workspace": { "id": "ws-1", "name": "wand", "cwd": "/repo" }
        }
        """.data(using: .utf8)!
        let task = try JSONDecoder().decode(WandBoardTask.self, from: json)
        XCTAssertEqual(task.id, "task-1")
        XCTAssertEqual(task.workspaceId, "ws-1")
        XCTAssertEqual(task.status, "doing")
        XCTAssertEqual(task.agent?.provider, "codex")
        XCTAssertEqual(task.workspace?.name, "wand")
        XCTAssertEqual(task.sessions.first?.id, "sess-1")
        XCTAssertTrue(task.sessions.first?.isStructured == true)
    }

    func testBoardTaskDecoderAllowsUnassignedProjectAndAgent() throws {
        let json = #"{"id":"task-2","title":"草稿"}"#.data(using: .utf8)!
        let task = try JSONDecoder().decode(WandBoardTask.self, from: json)
        XCTAssertNil(task.workspaceId)
        XCTAssertNil(task.agent)
        XCTAssertEqual(task.status, "todo")
        XCTAssertEqual(task.priority, "none")
        XCTAssertTrue(task.sessions.isEmpty)
        // 老服务端不返回 titleSource，按用户手写处理。
        XCTAssertEqual(task.titleSource, "user")
    }

    func testBoardTaskDecoderReadsAutoGeneratedTitleSource() throws {
        let json = #"{"id":"task-3","title":"根据描述生成的标题","titleSource":"auto"}"#.data(using: .utf8)!
        let task = try JSONDecoder().decode(WandBoardTask.self, from: json)
        XCTAssertEqual(task.titleSource, "auto")
    }

    func testBoardLabelsCoverColumns() {
        XCTAssertEqual(WandBoardStatus.todo.label, "待办")
        XCTAssertEqual(WandBoardStatus.doing.label, "进行中")
        XCTAssertEqual(WandBoardStatus.done.label, "已完成")
        XCTAssertEqual(WandBoardPriority.urgent.label, "紧急")
        XCTAssertEqual(wandBoardProviderLabel("pi"), "Pi")
        XCTAssertEqual(wandBoardEffortLabel("deep"), "深入")
    }


    func testSessionsGroupByTheAgentsThatRan() {
        let json = """
        {
          "id": "task-9",
          "title": "多 Agent",
          "agent": { "provider": "claude", "model": "opus", "thinkingEffort": "deep" },
          "sessions": [
            { "id": "s1", "provider": "claude", "title": "修登录", "status": "running", "model": "opus", "thinkingEffort": "deep" },
            { "id": "s2", "provider": "claude", "title": "补测试", "status": "exited", "model": "sonnet", "thinkingEffort": "off" },
            { "id": "s3", "provider": "codex", "title": "实现 API", "status": "idle", "model": "gpt-5", "thinkingEffort": "standard" }
          ]
        }
        """.data(using: .utf8)!
        let task = try! JSONDecoder().decode(WandBoardTask.self, from: json)
        let groups = wandBoardSessionGroups(sessions: task.sessions, assigned: task.agent)
        XCTAssertEqual(groups.map(\.provider), ["claude", "codex"])
        XCTAssertEqual(groups[0].sessions.map(\.id), ["s1", "s2"])
        XCTAssertEqual(groups[1].sessions.map(\.id), ["s3"])
        let pending = wandBoardSessionGroups(
            sessions: [],
            assigned: WandBoardTaskAgent(provider: "pi", model: "default", thinkingEffort: "off")
        )
        XCTAssertEqual(pending.count, 1)
        XCTAssertEqual(pending.first?.provider, "pi")
        XCTAssertTrue(pending.first?.sessions.isEmpty == true)
    }

}
